"$schema" = "https://starship.rs/config-schema.json"

add_newline = false
palette = "tomorrow_night_eighties"
scan_timeout = 10
command_timeout = 100
format = "$directory$git_branch$git_commit$git_state$git_status$character"
right_format = "$status$cmd_duration$jobs$direnv$package$python$rust"
continuation_prompt = "[∙](bright-black) "

[palettes.tomorrow_night_eighties]
foreground = "#cccccc"
comment = "#999999"
red = "#f2777a"
orange = "#f99157"
yellow = "#ffcc66"
green = "#99cc99"
cyan = "#66cccc"
blue = "#6699cc"
purple = "#cc99cc"
dir = "#0087af"
dir_anchor = "#00afff"
prompt_green = "#5fd700"
prompt_red = "#ff0000"

[directory]
style = "dir"
repo_root_style = "bold dir_anchor"
read_only_style = "prompt_red"
truncation_length = 8
truncate_to_repo = false
truncation_symbol = ""
read_only = " 🔒"
format = "[$path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = ""
style = "green"
truncation_length = 32
truncation_symbol = "…"
format = "[$branch(:$remote_branch)]($style) "

[git_commit]
style = "green"
commit_hash_length = 8
tag_disabled = false
tag_symbol = "#"
only_detached = true
format = "[@$hash$tag]($style) "

[git_state]
style = "red"
format = "[$state( $progress_current/$progress_total)]($style) "

[git_status]
format = "$ahead_behind$stashed$conflicted$staged$modified$deleted$renamed$untracked"
ahead = "[⇡${count}](green) "
behind = "[⇣${count}](green) "
diverged = "[⇣${behind_count}⇡${ahead_count}](green) "
stashed = "[*${count}](green) "
conflicted = "[~${count}](red) "
staged = "[+${count}](yellow) "
modified = "[!${count}](yellow) "
deleted = "[!${count}](yellow) "
renamed = "[!${count}](yellow) "
untracked = "[?${count}](blue) "

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold green)"
vimcmd_visual_symbol = "[V](bold green)"
vimcmd_replace_symbol = "[▶](bold green)"
vimcmd_replace_one_symbol = "[▶](bold green)"

[status]
disabled = false
format = "[$symbol$status]($style) "
symbol = "✘"
signal_symbol = "✘"
sigint_symbol = "✘"
style = "red"
map_symbol = true
recognize_signal_code = true
pipestatus = true
pipestatus_separator = "|"
pipestatus_format = '[$pipestatus]($style) '

[cmd_duration]
min_time = 3000
format = "[$duration]($style) "
style = "comment"
show_milliseconds = false

[jobs]
symbol = "✦"
style = "green"
format = "[$symbol$number]($style) "

[direnv]
disabled = false
symbol = ""
style = "yellow"
format = "[direnv $loaded/$allowed]($style) "

[package]
symbol = "󰏗 "
format = "[$symbol$version]($style) "

[python]
symbol = " "
format = "[$symbol$version]($style) "

[rust]
symbol = " "
format = "[$symbol$version]($style) "
