# Base16 Tomorrow Night Eighties - alacritty color config
# Chris Kempson (http://chriskempson.com)

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '#2d2d2d'
foreground = '#cccccc'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '#2d2d2d'
cursor = '#cccccc'

# Normal colors
[colors.normal]
black   = '#2d2d2d'
red     = '#f2777a'
green   = '#99cc99'
yellow  = '#ffcc66'
blue    = '#6699cc'
magenta = '#cc99cc'
cyan    = '#66cccc'
white   = '#cccccc'

# Bright colors
[colors.bright]
black   = '#999999'
red     = '#f99157'
green   = '#393939'
yellow  = '#515151'
blue    = '#b4b7b4'
magenta = '#e0e0e0'
cyan    = '#a3685a'
white   = '#ffffff'
